
export const LOGIN_USER="LOGIN_USER"

export const LOGIN_FAIL="LOGIN_FAIL"

export const REGISTER_USER="REGISTER_USER"
export const LOGAOUT_USER="LOGAOUT_USER"
export const GET_CURRENT="GET_CURRENT"
export const ERRORS="ERRORS"

export const ADD_SERVICE="ADD_SERVICE"
export const DELET_SERVICE="DELET_SERVICE"
export const EDITE_SERVICE="EDITE_SERVICE"
export const GET_SERVICE="GET_SERVICE"


export const ADD_FEEDBACK="ADD_FEEDBACK"
export const GET_FEEDBACK="GET_FEEDBACK"
export const DELET_FEEDBACK="DELET_FEEDBACK"


export const ADD_DEMANDE="ADD_DEMANDE"
export const GET_DEMANDES="GET_DEMANDES"
export const EDIT_DEMANDE="EDIT_DEMANDE"
export const DELET_DEMANDE="DELET_DEMANDE"


export const  DELETE_PROFILE="DELETE_PROFILE"
export const  SET_PROFILE="SET_PROFILE"
export const  SET_PROFILES="SET_PROFILES"

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_RESET = "FORGOT_PASSWORD_RESET";


export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";





export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM"
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";


export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const CLEAR_ERRORS="CLEAR_ERRORS"

